"""Point-in-time information timing audit for H4 swing and M15 confirmation signals.

Verifies programmatically and descriptively that:
FEATURE TIME < DECISION TIME < OUTCOME TIME
No feature or entry filter uses data from the future target outcome period.
"""

from __future__ import annotations

from typing import Any

import pandas as pd


def generate_timing_audit_report(
    h4_df: pd.DataFrame,
    aligned_m15: pd.DataFrame,
    target_series: pd.Series,
    sample_indices: list[int] | None = None,
    horizon_bars: int = 8,
) -> list[dict[str, Any]]:
    """Generate deterministic timing verification table for a sample of H4 decisions.

    Parameters
    ----------
    h4_df : pd.DataFrame
        H4 OHLCV DataFrame.
    aligned_m15 : pd.DataFrame
        Aligned M15 confirmation features generated by align_m15_with_h4_decisions.
    target_series : pd.Series
        Target labels (e.g. direction_vol_8).
    sample_indices : list[int], optional
        List of H4 bar row indices to sample. If None, picks 10 evenly spaced indices.
    horizon_bars : int, default 8
        Forward target horizon in H4 bars.

    Returns
    -------
    list[dict[str, Any]]
        List of audit records detailing exact timestamps, features, and outcome alignment.
    """
    ts_h4 = pd.to_datetime(h4_df["timestamp"], utc=True)
    n_bars = len(h4_df)

    if sample_indices is None:
        # Select 10 evenly spaced sample points from valid range
        # (avoid first 80 bars warmup and last horizon_bars tail)
        start_idx = 100
        end_idx = n_bars - horizon_bars - 1
        step = (end_idx - start_idx) // 10
        sample_indices = [start_idx + i * step for i in range(10)]

    records: list[dict[str, Any]] = []

    for idx in sample_indices:
        t_h4_start = ts_h4.iloc[idx]
        t_h4_close = t_h4_start + pd.Timedelta(hours=4)
        t_decision = t_h4_close

        # Feature cutoff: H4 bar closes at t_decision, so features use data up to t_decision
        t_feature_cutoff = t_decision

        # Target outcome timestamp: close of bar (idx + horizon_bars)
        target_bar_idx = idx + horizon_bars
        t_target_start = ts_h4.iloc[target_bar_idx]
        t_outcome = t_target_start + pd.Timedelta(hours=4)

        # M15 cutoff: latest completed M15 bar must have closed at or before t_decision
        m15_row = aligned_m15.iloc[idx]
        t_m15_matched = pd.Timestamp(m15_row["matched_m15_timestamp"])
        t_m15_cutoff = pd.Timestamp(m15_row["cutoff_m15"])

        # Target value
        val_target = target_series.iloc[idx]
        if val_target == 1.0:
            outcome_label = "LONG (+1.0)"
        elif val_target == -1.0:
            outcome_label = "SHORT (-1.0)"
        else:
            outcome_label = "EXCLUDED / FLAT"

        # Causal ordering check
        # Matched M15 bar timestamp < Decision Time
        # Decision Time < Target Outcome Time
        is_causal = (
            (t_m15_matched < t_decision)
            and (t_feature_cutoff <= t_decision)
            and (t_decision < t_outcome)
        )

        record = {
            "h4_bar_index": idx,
            "h4_bar_start": str(t_h4_start),
            "h4_decision_time": str(t_decision),
            "h4_feature_cutoff": str(t_feature_cutoff),
            "h4_target_horizon_bars": horizon_bars,
            "target_outcome_time": str(t_outcome),
            "latest_allowed_m15_timestamp": str(t_m15_cutoff),
            "actual_matched_m15_timestamp": str(t_m15_matched),
            "m15_features_used": {
                "candle_direction": float(m15_row["m15_candle_direction"]),
                "rsi_14": float(m15_row["m15_rsi_14"]),
                "dist_ema_20": float(m15_row["m15_dist_ema_20"]),
            },
            "actual_future_outcome": outcome_label,
            "causality_verified": is_causal,
        }
        records.append(record)

    return records
