"""MetaTrader 5 adapter package with demo execution and safety transports."""

from trading.adapters.mt5.client import MT5_TIMEFRAME_MAP, MT5ReadOnlyClient
from trading.adapters.mt5.forward import (
    ForwardDemoRunner,
    ForwardExecutionRecord,
    ForwardOperationalMetrics,
    ForwardPreflightReport,
    ForwardSignalRecord,
    ForwardValidationConfig,
)
from trading.adapters.mt5.normalizer import (
    MT5DataNormalizationError,
    mask_login,
    normalize_account_info,
    normalize_bar,
    normalize_symbol_info,
    normalize_terminal_info,
    normalize_tick,
    normalize_timestamp,
)
from trading.adapters.mt5.reconciliation import (
    PositionReconciliationError,
    ReconciliationItem,
    ReconciliationReport,
    ReconciliationStatus,
    reconcile_positions,
)
from trading.adapters.mt5.safety import (
    ACCOUNT_TRADE_MODE_CONTEST,
    ACCOUNT_TRADE_MODE_DEMO,
    ACCOUNT_TRADE_MODE_REAL,
    DEMO_ONLY,
    AccountTradeMode,
    DemoAccountVerificationError,
    DemoAccountVerifier,
    DemoExecutionNotAuthorizedError,
    DemoVerificationReport,
    LiveAccountForbiddenError,
    assert_demo_execution_authorized,
)
from trading.adapters.mt5.schemas import (
    MT5AccountMetadata,
    MT5BarData,
    MT5TerminalMetadata,
    MT5TickData,
    MT5Timeframe,
)
from trading.adapters.mt5.transport import (
    MT5DemoExecutionTransport,
    MT5ExecutionResponse,
    MT5ExecutionStatus,
)
from trading.execution.mt5_simulator import (
    SimulatedBrokerResponse,
    SimulatedMT5BrokerAdapter,
    SimulatedMT5Transport,
    SimulatedResponseStatus,
)

__all__ = [
    "ACCOUNT_TRADE_MODE_CONTEST",
    "ACCOUNT_TRADE_MODE_DEMO",
    "ACCOUNT_TRADE_MODE_REAL",
    "AccountTradeMode",
    "DEMO_ONLY",
    "DemoAccountVerificationError",
    "DemoAccountVerifier",
    "DemoExecutionNotAuthorizedError",
    "DemoVerificationReport",
    "ForwardDemoRunner",
    "ForwardExecutionRecord",
    "ForwardOperationalMetrics",
    "ForwardPreflightReport",
    "ForwardSignalRecord",
    "ForwardValidationConfig",
    "LiveAccountForbiddenError",
    "MT5AccountMetadata",
    "MT5BarData",
    "MT5DataNormalizationError",
    "MT5DemoExecutionTransport",
    "MT5ExecutionResponse",
    "MT5ExecutionStatus",
    "MT5ReadOnlyClient",
    "MT5TerminalMetadata",
    "MT5TickData",
    "MT5Timeframe",
    "MT5_TIMEFRAME_MAP",
    "PositionReconciliationError",
    "ReconciliationItem",
    "ReconciliationReport",
    "ReconciliationStatus",
    "SimulatedBrokerResponse",
    "SimulatedMT5BrokerAdapter",
    "SimulatedMT5Transport",
    "SimulatedResponseStatus",
    "assert_demo_execution_authorized",
    "mask_login",
    "normalize_account_info",
    "normalize_bar",
    "normalize_symbol_info",
    "normalize_terminal_info",
    "normalize_tick",
    "normalize_timestamp",
    "reconcile_positions",
]
